export const DEPUTY_GENRE_OPTIONS = [
  "Soul & Motown",
  "Funk & Disco",
  "Indie & Rock",
  "Alternative & Punk",
  "Pop & Classic Pop",
  "Dance & Electronic",
  "Reggae & Afrobeat",
  "RnB, HipHop & Garage",
  "80s",
  "90s",
  "00s",
  "Latin",
  "Folk & Acoustic",
  "Roaming",
  "Jazz & Swing",
  "Classical",
  "Israeli",
  "Other",
];
