import React, { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { backendUrl } from "../App";

const EMPTY_FORM = {
  entity: "TSC",
  type: "manual_adjustment",
  title: "",
  description: "",
  expectedDate: new Date().toISOString().slice(0, 10),
  amount: 0,
  direction: "out",
  status: "forecast",
  source: "manual",
  notes: "",
};

const entities = [
  "TSC",
  "BMM",
  "HSBC",
  "Monzo Joint",
  "Monzo Personal",
  "AMEX",
  "CBS",
  "HL Investment",
  "HSBC Investment",
  "Bitcoin",
  "Solana",
  "Ethereum",
  "True Potential Penson",
  "Aviva Pension",
];

const eventTypes = [
  "salary_out",
  "ni_out",
  "vat_out",
  "corporation_tax_out",
  "recurring_income",
  "recurring_expense",
  "manual_adjustment",
  "client_deposit_in",
  "client_balance_in",
  "supplier_payment_out",
];

const statuses = ["forecast", "confirmed", "paid", "cancelled", "ignored"];

const formatCurrency = (value = 0) =>
  new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    maximumFractionDigits: 2,
  }).format(Number(value || 0));

const formatDate = (date) => {
  if (!date) return "-";
  return new Date(date).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

const signedAmount = (event) =>
  event.direction === "out"
    ? -Number(event.amount || 0)
    : Number(event.amount || 0);

const matchesSearch = (event, search) => {
  const q = String(search || "").toLowerCase().trim();
  if (!q) return true;

  const amount = signedAmount(event);
  const amountText = String(Math.abs(Number(amount || 0)));
  const amountFixed = Math.abs(Number(amount || 0)).toFixed(2);
  const moneyText = formatCurrency(amount).toLowerCase();

  return [
    event.title,
    event.description,
    event.clientNames,
    event.actName,
    event.type,
    event.status,
    event.source,
    event.entity,
    event.notes,
    amountText,
    amountFixed,
    moneyText,
  ]
    .filter(Boolean)
    .some((value) => String(value).toLowerCase().includes(q));
};

const FinanceForecastEvents = () => {
  const [events, setEvents] = useState([]);
  const [form, setForm] = useState(EMPTY_FORM);
  const [editingId, setEditingId] = useState(null);

  const [entityFilter, setEntityFilter] = useState("TSC");
  const [statusFilter, setStatusFilter] = useState("forecast");
  const [search, setSearch] = useState("");

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [deletingId, setDeletingId] = useState("");
  const [error, setError] = useState("");
  const [successMessage, setSuccessMessage] = useState("");

  const filteredEvents = useMemo(() => {
    return events.filter((event) => matchesSearch(event, search));
  }, [events, search]);

  const fetchEvents = async () => {
    try {
      setLoading(true);
      setError("");
      setSuccessMessage("");

      const params = {};
      if (entityFilter !== "ALL") params.entity = entityFilter;
      if (statusFilter !== "ALL") params.status = statusFilter;

      const res = await axios.get(`${backendUrl}/api/finance/forecast-events`, {
        params,
      });

      if (res.data?.success) {
        setEvents(res.data.forecastEvents || []);
      } else {
        setError(res.data?.message || "Could not load forecast events");
      }
    } catch (err) {
      console.error("fetch forecast events error:", err);
      setError(err.response?.data?.message || err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEvents();
  }, [entityFilter, statusFilter]);

  const resetForm = () => {
    setForm(EMPTY_FORM);
    setEditingId(null);
    setError("");
  };

  const handleChange = (e) => {
    const { name, value } = e.target;

    setForm((prev) => ({
      ...prev,
      [name]: name === "amount" ? Number(value) : value,
    }));
  };

  const handleEdit = (event) => {
    if (event.isAutoGenerated) {
      setError("Auto-generated events should be changed from the booking/import.");
      return;
    }

    setEditingId(event._id);

    setForm({
      entity: event.entity || "TSC",
      type: event.type || "manual_adjustment",
      title: event.title || "",
      description: event.description || "",
      expectedDate: event.expectedDate
        ? new Date(event.expectedDate).toISOString().slice(0, 10)
        : new Date().toISOString().slice(0, 10),
      amount: Number(event.amount || 0),
      direction: event.direction || "out",
      status: event.status || "forecast",
      source: event.source || "manual",
      notes: event.notes || "",
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      setSaving(true);
      setError("");
      setSuccessMessage("");

      if (!form.title.trim()) {
        setError("Title is required");
        return;
      }

      if (!form.expectedDate) {
        setError("Expected date is required");
        return;
      }

      if (Number(form.amount || 0) <= 0) {
        setError("Amount must be greater than 0");
        return;
      }

      const payload = {
        ...form,
        amount: Math.abs(Number(form.amount || 0)),
      };

      if (editingId) {
        await axios.put(
          `${backendUrl}/api/finance/forecast-events/${editingId}`,
          payload,
        );
        setSuccessMessage("Forecast event updated.");
      } else {
        await axios.post(`${backendUrl}/api/finance/forecast-events`, payload);
        setSuccessMessage("Forecast event added.");
      }

      resetForm();
      await fetchEvents();
    } catch (err) {
      console.error("save forecast event error:", err);
      setError(err.response?.data?.message || err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (event) => {
    const message = event.isAutoGenerated
      ? "This is auto-generated. Safer option is to mark it ignored. Continue?"
      : "Delete this manual forecast event?";

    if (!window.confirm(message)) return;

    try {
      setDeletingId(event._id);
      setError("");
      setSuccessMessage("");

      if (event.isAutoGenerated) {
        await axios.put(`${backendUrl}/api/finance/forecast-events/${event._id}`, {
          status: "ignored",
        });
        setSuccessMessage("Auto-generated event marked as ignored.");
      } else {
        await axios.delete(`${backendUrl}/api/finance/forecast-events/${event._id}`);
        setSuccessMessage("Forecast event deleted.");
      }

      await fetchEvents();
    } catch (err) {
      console.error("delete/ignore forecast event error:", err);
      setError(err.response?.data?.message || err.message);
    } finally {
      setDeletingId("");
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 px-4 py-8 sm:px-8">
      <div className="mx-auto max-w-7xl">
        <div className="mb-6">
          <h1 className="text-2xl font-semibold text-gray-900">
            Forecast Events
          </h1>
          <p className="mt-1 text-sm text-gray-500">
            Add, edit and search expected cash movements.
          </p>
        </div>

        {error && (
          <div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">
            {error}
          </div>
        )}

        {successMessage && (
          <div className="mb-6 rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-700">
            {successMessage}
          </div>
        )}

        <div className="grid gap-6 lg:grid-cols-[420px_1fr]">
          <form
            onSubmit={handleSubmit}
            className="rounded-2xl bg-white p-5 shadow-sm"
          >
            <h2 className="mb-4 text-lg font-semibold text-gray-900">
              {editingId ? "Edit Forecast Event" : "Add Forecast Event"}
            </h2>

            <div className="space-y-4">
              <Input
                label="Title"
                name="title"
                value={form.title}
                onChange={handleChange}
                placeholder="Rhona salary"
              />

              <Input
                label="Description"
                name="description"
                value={form.description}
                onChange={handleChange}
                placeholder="Monthly salary"
              />

              <div className="grid grid-cols-2 gap-3">
                <Select
                  label="Entity"
                  name="entity"
                  value={form.entity}
                  onChange={handleChange}
                  options={entities}
                />

                <Select
                  label="Type"
                  name="type"
                  value={form.type}
                  onChange={handleChange}
                  options={eventTypes}
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <Input
                  label="Expected date"
                  name="expectedDate"
                  type="date"
                  value={form.expectedDate}
                  onChange={handleChange}
                />

                <Input
                  label="Amount"
                  name="amount"
                  type="number"
                  value={form.amount}
                  onChange={handleChange}
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <Select
                  label="Direction"
                  name="direction"
                  value={form.direction}
                  onChange={handleChange}
                  options={["in", "out"]}
                />

                <Select
                  label="Status"
                  name="status"
                  value={form.status}
                  onChange={handleChange}
                  options={statuses}
                />
              </div>

              <div>
                <label className="mb-1 block text-xs font-medium text-gray-600">
                  Notes
                </label>
                <textarea
                  name="notes"
                  value={form.notes}
                  onChange={handleChange}
                  rows="3"
                  className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm"
                />
              </div>

              <div className="flex gap-3">
                <button
                  type="submit"
                  disabled={saving}
                  className="rounded-lg bg-black px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
                >
                  {saving
                    ? "Saving..."
                    : editingId
                      ? "Update Event"
                      : "Add Event"}
                </button>

                {editingId && (
                  <button
                    type="button"
                    onClick={resetForm}
                    className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700"
                  >
                    Cancel
                  </button>
                )}
              </div>
            </div>
          </form>

          <div className="rounded-2xl bg-white p-5 shadow-sm">
            <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <h2 className="text-lg font-semibold text-gray-900">
                  Forecast Events
                </h2>
                <p className="text-sm text-gray-500">
                  {filteredEvents.length} of {events.length} events shown.
                </p>
              </div>

              <div className="flex flex-wrap gap-3">
                <Select
                  label="Entity"
                  value={entityFilter}
                  onChange={(e) => setEntityFilter(e.target.value)}
                  options={["ALL", ...entities]}
                />

                <Select
                  label="Status"
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  options={["ALL", ...statuses]}
                />
              </div>
            </div>

            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by title, client, amount, type, source..."
              className="mb-4 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm"
            />

            {loading ? (
              <div className="py-8 text-center text-sm text-gray-500">
                Loading forecast events...
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="min-w-full text-left text-sm">
                  <thead>
                    <tr className="border-b text-xs uppercase tracking-wide text-gray-500">
                      <th className="px-3 py-3">Date</th>
                      <th className="px-3 py-3">Title</th>
                      <th className="px-3 py-3">Type</th>
                      <th className="px-3 py-3">Status</th>
                      <th className="px-3 py-3">Source</th>
                      <th className="px-3 py-3 text-right">Amount</th>
                      <th className="px-3 py-3 text-right">Actions</th>
                    </tr>
                  </thead>

                  <tbody>
                    {filteredEvents.map((event) => (
                      <tr key={event._id} className="border-b last:border-0">
                        <td className="whitespace-nowrap px-3 py-3">
                          {formatDate(event.expectedDate)}
                        </td>
                        <td className="px-3 py-3">
                          <p className="font-medium text-gray-900">
                            {event.title}
                          </p>
                          <p className="text-xs text-gray-500">
                            {event.entity}
                            {event.clientNames ? ` · ${event.clientNames}` : ""}
                            {event.actName ? ` / ${event.actName}` : ""}
                          </p>
                        </td>
                        <td className="px-3 py-3 text-gray-500">
                          {event.type}
                        </td>
                        <td className="px-3 py-3">
                          <span className="rounded-full bg-gray-100 px-2 py-1 text-xs text-gray-700">
                            {event.status}
                          </span>
                        </td>
                        <td className="px-3 py-3 text-gray-500">
                          {event.isAutoGenerated ? "booking" : "manual"}
                        </td>
                        <td
                          className={`px-3 py-3 text-right font-medium ${
                            event.direction === "in"
                              ? "text-green-700"
                              : "text-red-700"
                          }`}
                        >
                          {formatCurrency(signedAmount(event))}
                        </td>
                        <td className="px-3 py-3 text-right">
                          {!event.isAutoGenerated && (
                            <button
                              onClick={() => handleEdit(event)}
                              className="mr-3 text-sm font-medium text-gray-700 underline"
                            >
                              Edit
                            </button>
                          )}

                          <button
                            onClick={() => handleDelete(event)}
                            disabled={deletingId === event._id}
                            className="text-sm font-medium text-red-600 underline disabled:opacity-50"
                          >
                            {deletingId === event._id
                              ? "Working..."
                              : event.isAutoGenerated
                                ? "Ignore"
                                : "Delete"}
                          </button>
                        </td>
                      </tr>
                    ))}

                    {!filteredEvents.length && (
                      <tr>
                        <td
                          colSpan="7"
                          className="px-3 py-8 text-center text-gray-500"
                        >
                          No forecast events found.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

const Input = ({ label, name, value, onChange, type = "text", placeholder }) => (
  <div>
    <label className="mb-1 block text-xs font-medium text-gray-600">
      {label}
    </label>
    <input
      type={type}
      name={name}
      value={value}
      onChange={onChange}
      placeholder={placeholder}
      className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm"
    />
  </div>
);

const Select = ({ label, name, value, onChange, options }) => (
  <div>
    {label && (
      <label className="mb-1 block text-xs font-medium text-gray-600">
        {label}
      </label>
    )}
    <select
      name={name}
      value={value}
      onChange={onChange}
      className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm"
    >
      {options.map((option) => (
        <option key={option} value={option}>
          {option}
        </option>
      ))}
    </select>
  </div>
);

export default FinanceForecastEvents;